export const MenuItems=[
    {
        title:'Badminton',
        path:'/Badminton',
        cName:'dropdown-link'
    },  
    {
        title:'Basketball',
        path:'/Basketball',
        cName:'dropdown-link'
    },  
    {
        title:'Carrom',
        path:'/Carrom',
        cName:'dropdown-link'
    },  
    {
        title:'Chess',
        path:'/Chess',
        cName:'dropdown-link'
    },  
    {
        title:'Cricket',
        path:'/Cricket',
        cName:'dropdown-link'
    },  
    {
        title:'Football',
        path:'/Football',
        cName:'dropdown-link'
    },  
    {
        title:'Squash',
        path:'/Squash',
        cName:'dropdown-link'
    },  
    {
        title:'TableTennis',
        path:'/TableTennis',
        cName:'dropdown-link'
    },  
    {
        title:'Tennis',
        path:'/Tennis',
        cName:'dropdown-link'
    },  
    {
        title:'Volleyball',
        path:'/Volleyball',
        cName:'dropdown-link'
    },  
]